### PR TITLE
Add reference standard

### PR DESCRIPTION
**Pull request by kingthorin**
In follow-up to:
- https://github.com/OWASP/ASVS/pull/804
- https://github.com/OWASP/ASVS/issues/715

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by tghosth** [comment]
Please can you check that this matches the final ASVS text

**Comment by kingthorin** [comment]
ACK you're right, I think I copy/pasted from a PR not from the live README. 

Tweak coming. Note one minor difference will be the link on the final line, since in this context it refers to something that is non-local.

**Comment by kingthorin** [comment]
Done

**Comment by tghosth** [comment]
looks good to me, I will merge. Thanks @kingthorin

**Review by Yedfree — APPROVED** [review]

**Pull request merged**
