### PR TITLE
Update tab_asvsusers.md

### PR DESCRIPTION
**Pull request by dholzapfel-nviso**
Add NVISO as a user

### CODE REVIEW

**Comment by tghosth** [comment]
@dholzapfel-nviso are you ok with the changes I made?

**Comment by dholzapfel-nviso** [comment]
@tghosth Sure. I tried to align the phrasing with the other sentence, but I'm ok with the changes.

**Comment by dholzapfel-nviso** [comment]
@tghosth : Anything else that I can do? Or can we merge the change?

**Comment by tghosth** [comment]
Sorry, fell between the cracks. Got this in now

**Pull request merged**
